version: "3.9"

services:
  abraca-server:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.server
    environment:
      HOST: 0.0.0.0
      PORT: 8080
    ports:
      - "8080:8080"
